- name: Configure webserver with nginx
  hosts: webservers
  become: true
  tasks:
    - name: install nginx
      yum: name=nginx update_cache=yes

    - name: create /etc/nginx/sites-available/
      file: 
        path: /etc/nginx/sites-available/
        state: directory
        mode: 0644

    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default

    - name: create /etc/nginx/sites-enabled/
      file: 
        path: /etc/nginx/sites-enabled/
        state: directory
        mode: 0644

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
    
    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

    - name: restart nginx
      service: name=nginx state=restarted